name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Go (or replace with your language runtime)
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Run Tests
        run: go test ./...
      - name: Build Binary
        run: |
          GOOS=$(echo "${{ matrix.os }}" | sed 's/-latest//')
          GOARCH=amd64
          go build -o myapp-${GOOS}-${GOARCH} .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ matrix.os }}
          path: myapp-${{ matrix.os }}-amd64
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: myapp-*/myapp-*
          tag_name: ${{ github.sha }}
          body: "Automated release from the release branch."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}